export enum ActionType {
  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_UPDATED = 'LEAD_UPDATED',
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  LEAD_REASSIGNED = 'LEAD_REASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  REMARK_ADDED = 'REMARK_ADDED',
  REMARK_EDITED = 'REMARK_EDITED',
  REMARK_DELETED = 'REMARK_DELETED',
  FOLLOWUP_SCHEDULED = 'FOLLOWUP_SCHEDULED',
  FOLLOWUP_COMPLETED = 'FOLLOWUP_COMPLETED',
  FOLLOWUP_CANCELLED = 'FOLLOWUP_CANCELLED',
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',
  LEAD_WON = 'LEAD_WON',
  LEAD_LOST = 'LEAD_LOST',
}

export const ActionTypeLabels: Record<ActionType, string> = {
  [ActionType.LEAD_CREATED]: 'Lead Created',
  [ActionType.LEAD_UPDATED]: 'Lead Updated',
  [ActionType.LEAD_ASSIGNED]: 'Lead Assigned',
  [ActionType.LEAD_REASSIGNED]: 'Lead Reassigned',
  [ActionType.STATUS_CHANGED]: 'Status Changed',
  [ActionType.REMARK_ADDED]: 'Remark Added',
  [ActionType.REMARK_EDITED]: 'Remark Edited',
  [ActionType.REMARK_DELETED]: 'Remark Deleted',
  [ActionType.FOLLOWUP_SCHEDULED]: 'Follow-up Scheduled',
  [ActionType.FOLLOWUP_COMPLETED]: 'Follow-up Completed',
  [ActionType.FOLLOWUP_CANCELLED]: 'Follow-up Cancelled',
  [ActionType.FILE_UPLOADED]: 'File Uploaded',
  [ActionType.FILE_DELETED]: 'File Deleted',
  [ActionType.LEAD_WON]: 'Lead Won',
  [ActionType.LEAD_LOST]: 'Lead Lost',
};
