export enum AuditActionType {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_UPDATED = 'LEAD_UPDATED',
  LEAD_DELETED = 'LEAD_DELETED',
  LEAD_RESTORED = 'LEAD_RESTORED',
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  LEAD_REASSIGNED = 'LEAD_REASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  REMARK_CREATED = 'REMARK_CREATED',
  REMARK_UPDATED = 'REMARK_UPDATED',
  REMARK_DELETED = 'REMARK_DELETED',
  FOLLOWUP_CREATED = 'FOLLOWUP_CREATED',
  FOLLOWUP_COMPLETED = 'FOLLOWUP_COMPLETED',
  FOLLOWUP_CANCELLED = 'FOLLOWUP_CANCELLED',
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',
  EXPORT_GENERATED = 'EXPORT_GENERATED',
  IMPORT_COMPLETED = 'IMPORT_COMPLETED',
  TAG_CREATED = 'TAG_CREATED',
  TAG_DELETED = 'TAG_DELETED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
}

export const AuditActionTypeLabels: Record<AuditActionType, string> = {
  [AuditActionType.USER_CREATED]: 'User Created',
  [AuditActionType.USER_UPDATED]: 'User Updated',
  [AuditActionType.USER_DEACTIVATED]: 'User Deactivated',
  [AuditActionType.PASSWORD_RESET]: 'Password Reset',
  [AuditActionType.LOGIN_SUCCESS]: 'Login Success',
  [AuditActionType.LOGIN_FAILED]: 'Login Failed',
  [AuditActionType.LOGOUT]: 'Logout',
  [AuditActionType.LEAD_CREATED]: 'Lead Created',
  [AuditActionType.LEAD_UPDATED]: 'Lead Updated',
  [AuditActionType.LEAD_DELETED]: 'Lead Deleted',
  [AuditActionType.LEAD_RESTORED]: 'Lead Restored',
  [AuditActionType.LEAD_ASSIGNED]: 'Lead Assigned',
  [AuditActionType.LEAD_REASSIGNED]: 'Lead Reassigned',
  [AuditActionType.STATUS_CHANGED]: 'Status Changed',
  [AuditActionType.REMARK_CREATED]: 'Remark Created',
  [AuditActionType.REMARK_UPDATED]: 'Remark Updated',
  [AuditActionType.REMARK_DELETED]: 'Remark Deleted',
  [AuditActionType.FOLLOWUP_CREATED]: 'Follow-up Created',
  [AuditActionType.FOLLOWUP_COMPLETED]: 'Follow-up Completed',
  [AuditActionType.FOLLOWUP_CANCELLED]: 'Follow-up Cancelled',
  [AuditActionType.FILE_UPLOADED]: 'File Uploaded',
  [AuditActionType.FILE_DELETED]: 'File Deleted',
  [AuditActionType.EXPORT_GENERATED]: 'Export Generated',
  [AuditActionType.IMPORT_COMPLETED]: 'Import Completed',
  [AuditActionType.TAG_CREATED]: 'Tag Created',
  [AuditActionType.TAG_DELETED]: 'Tag Deleted',
  [AuditActionType.SETTINGS_UPDATED]: 'Settings Updated',
};
